image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install jekyll jekyll-paginate
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

title: Deducely
blog_title: Deducely Musings
email: hello@deducely.com

permalink: pretty
url: "http://deducely.com" # the base hostname & protocol for your site
twitter_username: deducely

# Build settings
markdown: kramdown